{
    "name": "IOMR Commission Management",
    "version": "18.0.1.0.0",
    "author": "IOMR",
    "category": "Sales/Commission",
    "license": "AGPL-3",
    "depends": [
        "base",
        "mail",
        "hr",
        "web",
    ],
    "data": [
        "security/commission_security.xml",
        "security/ir.model.access.csv",
        "data/commission_sequence.xml",
        "data/commission_policy_data.xml",
        "views/commission_menu.xml",
        "views/commission_member_views.xml",
        "views/commission_policy_views.xml",
        "views/commission_target_views.xml",
        "views/commission_sale_views.xml",
        "views/commission_result_views.xml",
    ],
    "demo": [],
    "installable": True,
    "application": True,
    "auto_install": False,
}
